# Generated by Django 5.2.1 on 2025-06-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizattempt',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
