# Generated by Django 5.1.6 on 2025-05-02 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_created_at_quiz_description_quiz_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_id',
        ),
    ]
