# Generated by Django 5.1.6 on 2025-05-02 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_quiz_quiz_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='diffuculty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
    ]
